Repository nextcloud-libraries/nextcloud-logger, pull requests merged in 2023-09, with the labels that each got.

#550 Use the original property for debug and loglevel
  lib/LoggerBuilder.ts
  package.json
  tests/LoggerBuilder.spec.ts
Labels: 3. to review

#551 Remove permission check in publish workflows
  .github/workflows/documentation.yml
  package.json
Labels: 3. to review

#557 chore: Add missing description to package
  README.md
  package.json
Labels: bug

#553 chore: Migrate to vite and `@nextcloud/vite-config` to also build an ESM entry point
  babel.config.js
  package-lock.json
  package.json
  vite.config.mjs
Labels: enhancement, 3. to review
